# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Jumping Rivers
tagline:             'Pre-course material'
description:         'Pre-course information to help you make the most of the day.'
url:                 https://www.jumpingrivers.com
baseurl:             ''
paginate:            5
exclude:
  - introduction.Rmd
  - "*.Rmd"

# About/contact
author:
  name:              Jumping Rivers
  url:               https://www.jumpingrivers.com
  email:             info@jumpingrivers.com

# Custom vars
version:             1.0.0
